import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Theme } from "@yakad/ui";
import { Xpanel } from "@yakad/x";
import NavList from "@/components/NavList";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <Theme darkStyle="dark">
                    <Xpanel name="Yakad Docs" navigationChildren={<NavList />}>
                        {children}
                    </Xpanel>
                </Theme>
            </body>
        </html>
    );
}
